language:
  sentence 
  | #empty
  ;
sentence:
  data_literal+
  ;
data_literal:
  list_literal
  | tuple_literal
  | map_literal
  | primitive_literal
  ;
primitive_literal:
  integer
  | atom
  | boolean
  ;
list_literal:
  '[' [ data_literal ( ',' data_literal )* ] ']'
  ;
tuple_literal:
  '{' [ data_literal ( ',' data_literal )* ] '}'
  ;
map_literal:
  '%{' [ key_pair ( ',' key_pair )* ] '}'
  ;
key_pair:
  data_literal '=>' data_literal
  | key data_literal
  ;
integer:
  digit ( digit | '_' )*
  ;
atom:
  ':' alphabetic ( alphanumeric | '_' )*
  ;
key:
  alphabetic ( alphanumeric | '_' )* ':'
  ;
boolean:
  'true' | 'false'
  ;
digit:
  '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
  ;
alphabetic:
  'a' | 'b' | 'c' | ... | 'z' | 'A' | 'B' | ... | 'Z'
  ;
alphanumeric:
  alphabetic | digit
  ;